// WARNING: DO NOT EDIT THIS FILE, IT IS AUTOGENERATED
module.exports = {
  addonType: "effect",
  id: "piranha305_football-uniform",
  name: "Football Uniform",
  version: "1.0.0.0",
  category:
    // "blend",
    // "distortion",
    // "normal-mapping",
    // "tiling",
    // "other",
    "color",
  author: "piranha305",
  website: "https://www.construct.net",
  documentation: "https://www.construct.net",
  description: "A custom shader that does multi color swapping for a football uniform.",
  supportedRenderers: ["webgl", "webgl2", "webgpu"],
  blendsBackground: false,
  usesDepth: false,
  crossSampling: false,
  preservesOpaqueness: true,
  animated: false,
  mustPredraw: false,
  extendBox: {
    horizontal: 0,
    vertical: 0,
  },
  isDeprecated: false,
  parameters: [
    /*
    {
      type:
        "float"
        "percent"
        "color"
      ,
      id: "property_id",
      value: 0,
      uniform: "uPropertyId",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Property Name",
      desc: "Property Description",
    }
    */
    {
      type: "color",
      id: "helmet",
      value: [0,0,1],
      uniform: "helmet",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Helmet Color",
      desc: "The color of the helmet. (replaces blue [0,0,1])",
    },
    {
      type: "color",
      id: "helmet2",
      value: [0,0,0],
      uniform: "helmet2",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Helmet Secondary Color",
      desc: "The secondary color of the helmet. (replaces black [0,0,0])",
    },
    {
      type: "color",
      id: "helmet3",
      value: [0.5,0.5,0.5],
      uniform: "helmet3",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Helmet Third Color",
      desc: "The third color of the helmet. (replaces gray [0.5,0.5,0.5])",
    },
    {
      type: "color",
      id: "facemask",
      value: [1,1,0],
      uniform: "facemask",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Facemask Color",
      desc: "The color of the facemask. (replaces yellow [1,1,0])",
    },
    {
      type: "color",
      id: "jersey",
      value: [1,0,0],
      uniform: "jersey",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Jersey Color",
      desc: "The color of the jersey. (replaces red [1,0,0])",
    },
    {
      type: "color",
      id: "jersey2",
      value: [1,0,1],
      uniform: "jersey2",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Jersey Secondary Color",
      desc: "The secondary color of the jersey. (replaces magenta [1,0,1])",
    },
    {
      type: "color",
      id: "pants",
      value: [0,1,0],
      uniform: "pants",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Pants Color",
      desc: "The color of the pants. (replaces green [0,1,0])",
    },
    {
      type: "color",
      id: "shoes",
      value: [0,1,1],
      uniform: "shoes",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Shoes Color",
      desc: "The color of the shoes. (replaces cyan [0,1,1])",
    },
    {
      type: "color",
      id: "skin",
      value: [1,1,1],
      uniform: "skin",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Skin Color",
      desc: "The color of the skin. (replaces white [1,1,1])",
    },
    {
      type: "float",
      id: "tolerance",
      value: 0.1,
      uniform: "tolerance",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Tolerance",
      desc: "The tolerance of the color swapping. (0.0 - 1.0)",
    },
    {
      type: "float",
      id: "intensity",
      value: 1.0,
      uniform: "intensity",
      // precision: "lowp" // defaults to lowp if omitted
      interpolatable: true,
      name: "Intensity",
      desc: "The intensity of the color swapping. (0.0 - 1.0)",
    }
  ],
};
